export const NATIONALITIES: Array<{ code: string; label: string }> = [
  { code: "ITA", label: "Italia" },
  { code: "ALB", label: "Albania" },
  { code: "ARG", label: "Argentina" },
  { code: "BIH", label: "Bosnia-Erzegovina" },
  { code: "BRA", label: "Brasile" },
  { code: "BGR", label: "Bulgaria" },
  { code: "CMR", label: "Camerun" },
  { code: "COL", label: "Colombia" },
  { code: "CIV", label: "Costa d'Avorio" },
  { code: "HRV", label: "Croazia" },
  { code: "EGY", label: "Egitto" },
  { code: "FRA", label: "Francia" },
  { code: "GHA", label: "Ghana" },
  { code: "DEU", label: "Germania" },
  { code: "MAR", label: "Marocco" },
  { code: "MDA", label: "Moldavia" },
  { code: "MKD", label: "Macedonia del Nord" },
  { code: "NGA", label: "Nigeria" },
  { code: "POL", label: "Polonia" },
  { code: "PRT", label: "Portogallo" },
  { code: "GBR", label: "Regno Unito" },
  { code: "ROU", label: "Romania" },
  { code: "SEN", label: "Senegal" },
  { code: "SRB", label: "Serbia" },
  { code: "ESP", label: "Spagna" },
  { code: "TUN", label: "Tunisia" },
  { code: "UKR", label: "Ucraina" },
  { code: "URY", label: "Uruguay" },
  { code: "VEN", label: "Venezuela" },
];
